name: Setting Up Firebase CI/CD for Different Channels

on:
  push:
    branches:
      - UAT
      - Dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build your web application
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: |
          # Deploy your application to Firebase Hosting
          if [ "${{ github.ref}}" = "refs/heads/main" ]; then
            CHANEL="main"
          elif [ "${{ github.ref}}" = "ref/heads/Dev" ]; then
            CHANEL="dev"
          else
            # If the branch is not main, Dev, or staging, exit without deploying
            echo "Branch not set up for deployment."
            exit 0
          fi

          #Deploy your application to the specified Hosting Channel
          firebase hosting:channel:deploy "$CHANNEL" --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
