name: Setting Up Firebase CI/CD for Different Channels

on:
  push:
    branches:
      - UAT
      - Dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build your web application
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: |
          # Deploy your application to Firebase Hosting
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
